[mainConfig]
appName = "MyChat"
host = "0.0.0.0"
port = 8000

[emailConfig]
authcode = "letluzytpsexdhcj"
email = "3189769526@qq.com"

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "root"
password = "lkt20031206"
databaseName = "MyChat"
charset =  "utf8mb4"


[jwtConfig]
 expire_duration= 8760
 issuer= "huanheart"
 subject= "MyChat"
 key= "MyChat-v1"

