[mainConfig]
appName = "MyMusicPlatform"
host = "0.0.0.0"
port = 8000

# musicFilePath = "/static"
# 真实的一个服务器文件路径
musicFilePath = "D:/MyMusicPlatform/test"
# 访问的服务器的一个相对地址
httpFilePath ="/test"
# 文件存储ip地址，一般是本地（后续接入oss接口）
musicFileIp = "192.168.15.1"


[emailConfig]
authcode = "letluzytpsexdhcj"
email = "3189769526@qq.com"

[redisConfig]
host = "127.0.0.1"
port = 6379
password = ""
db = 0

[mysqlConfig]
host = "127.0.0.1"
port = 3306
user = "root"
password = "lkt20031206"
databaseName = "MyChat"
charset =  "utf8mb4"


[jwtConfig]
 expire_duration= 8760
 issuer= "huanheart"
 subject= "MyChat"
 key= "MyChat-v1"

[rabbitmqConfig]
  host= "192.168.15.129"
  port= 5672
  username= "root"
  password= "123456"
  vhost= "/"


